services:
  api:
    build:
      context: .
      dockerfile: dockerfile
      tags:
        - 'arkdich/nodejs-auth-service'
    container_name: nodejs-auth-service-container
    environment:
      - PORT_DB=5432
      - DB_HOST=database
    ports:
      - '4000:4000'
